#!/bin/bash

TAG="setup local credential repo"

function err() {
	echo "${TAG} : $1 !!";
	exit 1
}

echo "${TAG} : input dire ($1)"
[ -z $1 ] && err "input directory is missing"

cd $1

echo "${TAG} :starting..."
rm -fr /workspace/gpg-keys/
mkdir -p /workspace/results/packages/
rm -fr /workspace/results/packages/*
echo "${TAG} : work dir cleanup done..."

cp -fr *.deb /workspace/results/packages/ 2>&1  || err "deb package copying failed"

# generate key: make sure the existing script
gen_sign_key || err "gen_sign_key failed"

GNUPGHOME=/workspace/gpg-keys/.gnupg gen_app_apt_repo || err "creating local repo failed"

# we are make use existing scripts. but we dont need local.list
sudo rm -fr /etc/apt/sources.list.d/local.list || err "removing local.list failed"

exit 0
